# Generated by Django 5.0.6 on 2024-08-10 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_remove_booking_completed_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
